// Define the type for a device listing

export interface DeviceInfo {
  name: string;
  description: string;
  model: string;
  quality: string;
  suggested_price?: number;
  b3tr_reward?: number;
}

export type DeviceListing = DeviceInfo & {
  id: number;
  price: number;
  condition: string;
  location: string;
  imageLinks: string[];
};

export const mockListings: DeviceListing[] = [
  {
    id: 1,
    name: "iPhone 12",
    description: "Great condition iPhone 12",
    price: 400,
    condition: "Used",
    location: "New York",
    model: "A2172",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=1",
      "https://picsum.photos/800/1000?random=2",
      "https://picsum.photos/800/1000?random=3",
    ],
    b3tr_reward: 50,
  },
  {
    id: 2,
    name: "Samsung TV",
    description: "Large Samsung Smart TV",
    price: 300,
    condition: "Broken",
    location: "Los Angeles",
    model: "QN55Q60A",
    quality: "Fair",
    imageLinks: [
      "https://picsum.photos/800/1000?random=4",
      "https://picsum.photos/800/1000?random=5",
      "https://picsum.photos/800/1000?random=6",
    ],
    b3tr_reward: 50,
  },
  {
    id: 3,
    name: "MacBook Pro",
    description: "Powerful MacBook Pro laptop",
    price: 800,
    condition: "Like New",
    location: "Chicago",
    model: "A2338",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=7",
      "https://picsum.photos/800/1000?random=8",
      "https://picsum.photos/800/1000?random=9",
    ],
    b3tr_reward: 50,
  },
  {
    id: 4,
    name: "Google Pixel 5",
    description: "Slightly used Google Pixel 5",
    price: 350,
    condition: "Used",
    location: "San Francisco",
    model: "GD1YQ",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=10",
      "https://picsum.photos/800/1000?random=11",
      "https://picsum.photos/800/1000?random=12",
    ],
    b3tr_reward: 50,
  },
  {
    id: 5,
    name: "Dell XPS 13",
    description: "High performance Dell XPS 13",
    price: 900,
    condition: "Like New",
    location: "Austin",
    model: "9310",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=13",
      "https://picsum.photos/800/1000?random=14",
      "https://picsum.photos/800/1000?random=15",
    ],
    b3tr_reward: 50,
  },
  {
    id: 6,
    name: "PlayStation 5",
    description: "Next-gen PlayStation 5 console",
    price: 500,
    condition: "Used",
    location: "Miami",
    model: "CFI-1015A",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=16",
      "https://picsum.photos/800/1000?random=17",
      "https://picsum.photos/800/1000?random=18",
    ],
    b3tr_reward: 50,
  },
  {
    id: 7,
    name: "iPad Pro",
    description: "Latest model iPad Pro",
    price: 600,
    condition: "Like New",
    location: "Seattle",
    model: "A2378",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=19",
      "https://picsum.photos/800/1000?random=20",
      "https://picsum.photos/800/1000?random=21",
    ],
    b3tr_reward: 50,
  },
  {
    id: 8,
    name: "HP Spectre x360",
    description: "Versatile HP Spectre x360",
    price: 700,
    condition: "Used",
    location: "Denver",
    model: "13-aw0205tu",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=22",
      "https://picsum.photos/800/1000?random=23",
      "https://picsum.photos/800/1000?random=24",
    ],
    b3tr_reward: 50,
  },
  {
    id: 9,
    name: "Microsoft Surface Laptop 4",
    description: "Powerful Surface Laptop 4",
    price: 850,
    condition: "Like New",
    location: "Portland",
    model: "5EB-00001",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=25",
      "https://picsum.photos/800/1000?random=26",
      "https://picsum.photos/800/1000?random=27",
    ],
    b3tr_reward: 50,
  },
  {
    id: 10,
    name: "Nintendo Switch",
    description: "Versatile Nintendo Switch",
    price: 250,
    condition: "Used",
    location: "Boston",
    model: "HAC-001(-01)",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=28",
      "https://picsum.photos/800/1000?random=29",
      "https://picsum.photos/800/1000?random=30",
    ],
    b3tr_reward: 50,
  },
  {
    id: 11,
    name: "Sony Alpha a7 III",
    description: "Full-frame mirrorless camera",
    price: 1800,
    condition: "Like New",
    location: "San Diego",
    model: "ILCE-7M3",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=31",
      "https://picsum.photos/800/1000?random=32",
      "https://picsum.photos/800/1000?random=33",
    ],
    b3tr_reward: 50,
  },
  {
    id: 12,
    name: "Fitbit Charge 4",
    description: "Fitness tracker with GPS",
    price: 100,
    condition: "Used",
    location: "Atlanta",
    model: "FB417",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=34",
      "https://picsum.photos/800/1000?random=35",
      "https://picsum.photos/800/1000?random=36",
    ],
    b3tr_reward: 50,
  },
  {
    id: 13,
    name: "GoPro HERO9 Black",
    description: "Action camera with 5K video",
    price: 350,
    condition: "Like New",
    location: "Orlando",
    model: "CHDHX-901",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=37",
      "https://picsum.photos/800/1000?random=38",
      "https://picsum.photos/800/1000?random=39",
    ],
    b3tr_reward: 50,
  },
  {
    id: 14,
    name: "Canon EOS R5",
    description: "Professional-grade mirrorless camera",
    price: 3500,
    condition: "Like New",
    location: "Phoenix",
    model: "EOS R5",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=40",
      "https://picsum.photos/800/1000?random=41",
      "https://picsum.photos/800/1000?random=42",
    ],
    b3tr_reward: 50,
  },
  {
    id: 15,
    name: "JBL Flip 5",
    description: "Portable Bluetooth speaker",
    price: 100,
    condition: "Used",
    location: "Nashville",
    model: "FLIP5",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=43",
      "https://picsum.photos/800/1000?random=44",
      "https://picsum.photos/800/1000?random=45",
    ],
    b3tr_reward: 50,
  },
  {
    id: 16,
    name: "Bose QuietComfort 35 II",
    description: "Noise-cancelling headphones",
    price: 250,
    condition: "Used",
    location: "Dallas",
    model: "QC35 II",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=46",
      "https://picsum.photos/800/1000?random=47",
      "https://picsum.photos/800/1000?random=48",
    ],
    b3tr_reward: 50,
  },
  {
    id: 17,
    name: "Amazon Kindle Paperwhite",
    description: "Waterproof e-reader",
    price: 130,
    condition: "Like New",
    location: "Houston",
    model: "PQ94WIF",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=49",
      "https://picsum.photos/800/1000?random=50",
      "https://picsum.photos/800/1000?random=51",
    ],
    b3tr_reward: 50,
  },
  {
    id: 18,
    name: "Garmin Fenix 6X",
    description: "Rugged multisport GPS watch",
    price: 600,
    condition: "Used",
    location: "Philadelphia",
    model: "010-02157-00",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=52",
      "https://picsum.photos/800/1000?random=53",
      "https://picsum.photos/800/1000?random=54",
    ],
    b3tr_reward: 50,
  },
  {
    id: 19,
    name: "Razer Blade 15",
    description: "Gaming laptop with RTX 3070",
    price: 2000,
    condition: "Like New",
    location: "San Antonio",
    model: "RZ09-0367",
    quality: "Excellent",
    imageLinks: [
      "https://picsum.photos/800/1000?random=55",
      "https://picsum.photos/800/1000?random=56",
      "https://picsum.photos/800/1000?random=57",
    ],
    b3tr_reward: 50,
  },
  {
    id: 20,
    name: "Apple Watch Series 6",
    description: "Smartwatch with ECG",
    price: 350,
    condition: "Used",
    location: "Charlotte",
    model: "A2294",
    quality: "Good",
    imageLinks: [
      "https://picsum.photos/800/1000?random=58",
      "https://picsum.photos/800/1000?random=59",
      "https://picsum.photos/800/1000?random=60",
    ],
    b3tr_reward: 50,
  },
];
